### ISSUE TITLE
Add ability to select on which nodes BGP will be enabled

### ISSUE THREAD

**Issue by invidian** [packethost/packet-ccm#100]
In some large clusters, one may want to have dedicated pool of Ingress nodes, which will be handling ingress traffic. CCM currently enables BGP on all nodes in the cluster.

In [Lokomotive](https://github.com/kinvolk/lokomotive) we allow users to disable BGP per-worker pool, if needed, for example for security reasons.

It would be great if one could configure a node selector in the CCM, which would select on which nodes BGP should be enabled.

**Comment by deitch** [comment]
Why can you not do it now? The bgp speakers are enabled in the loadbalancers.yaml deployment manifest. Can you not just modify the daemonset, updating its selectors, to control where the speakers are deployed?

**Comment by invidian** [comment]
>Why can you not do it now? The bgp speakers are enabled in the loadbalancers.yaml deployment manifest. Can you not just modify the daemonset, updating its selectors, to control where the speakers are deployed?

This has security implications, if any node of the cluster gets compromised, it may start capturing the traffic. Using node selector with combination of privileged labels like `role` would prevent that.

**Comment by deitch** [comment]
I don't understand. All that ccm does is configure the configmap; it is metallb's DaemonSet that does the speaker announcements.

Or do you mean enabling it at a Packet API level, which the ccm owns?

**Comment by invidian** [comment]
I mean enabling it on the ~Packet~ Equinix Metal API level, sorry If I wasn't clear.

**Comment by deitch** [comment]
That makes sense. What would the API look like? How would you tell CCM "enable it only on these nodes"? CCM mostly is configured via some combination of:

* a single secret
* cli flags
* env vars

It also writes annotations to nodes, so it could be configured to look for a specific annotation or label. 

But the key question is, how would you tell it, "don't use your default behaviour, use this one"?

**Comment by invidian** [comment]
>It also writes annotations to nodes, so it could be configured to look for a specific annotation or label.

I think the annotations can be written to all Node objects I don't mind that.

But creating BGP session would ideally be limited by a label selector, similar to `kubectl get -l`:
```
  -l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)
```

The selector would match all nodes by default to preserve existing behavior. And selector could be configured the same as other CCM options, so via secret option, cli flag or env vars, to stay consistent.

What do you think?

**Comment by deitch** [comment]
I think that label selector is fine. How do you pass it to ccm without making it messy?

**Comment by invidian** [comment]
>How do you pass it to ccm without making it messy?

Do you mean from user point of view or implementation point of view?

From user point of view, something like `key1=value1,key2=value2` can be used in a single config field/env var etc.

From implementation point of view, I'm not sure yet, I didn't look at the code, but as far as I know, `NewFilteredSharedInformerFactory` can be used for it for example.

**Comment by deitch** [comment]
No, code is easy. User point of view. What would it look like in all three scenarios: CLI, env var, secret config?

**Comment by invidian** [comment]
Right. So something like:
- env var: `PACKET_BGP_NODE_SELECTOR=key1=value1,key2=value2`
- secret config key: `bgpNodeSelector: key1=value1,key2=value2`
- CLI: `--bgp-node-selector key1=value1,key2=value2`

Name of option can be changed, `BGP_NODE_SELECTOR` is the first thing which comes to my mind.

**Comment by deitch** [comment]
And those would be logically ANDed, like selectors on other k8s resources?

**Comment by invidian** [comment]
>And those would be logically ANDed, like selectors on other k8s resources?

Yes.

**Comment by deitch** [comment]
Makes sense. We should try and schedule it in, but no one would argue with a PR. Want to open one?

**Comment by invidian** [comment]
>Makes sense. We should try and schedule it in, but no one would argue with a PR. Want to open one?

Yes, I think I can do it :)

**Comment by invidian** [comment]
>No, code is easy.

Hmm, I'm not sure about that :smile: As your `nodeReconciler` type currently takes a list of nodes to work on, it does not have a direct access to the informer. Also the `timerLoop` function currently just lists all nodes and passes them to the `nodeReconciler`. Any ideas how to approach that in a reasonable way?

Implementing config handling is easy:
```diff
diff --git main.go main.go
index ebbb16b..a95a70c 100644
--- main.go
+++ main.go
@@ -10,6 +10,7 @@ import (
        "strconv"
        "time"

+       "k8s.io/apimachinery/pkg/labels"
        cliflag "k8s.io/component-base/cli/flag"
        "k8s.io/component-base/logs"
        _ "k8s.io/component-base/metrics/prometheus/clientgo" // for client metric registration
@@ -33,6 +34,7 @@ const (
        envVarAnnotationPeerIPs      = "PACKET_ANNOTATION_PEER_IPS"
        envVarEIPTag                 = "PACKET_EIP_TAG"
        envVarAPIServerPort          = "PACKET_API_SERVER_PORT"
+       envVarBGPNodeSelector        = "PACKET_BGP_NODE_SELECTOR"
        defaultLoadBalancerConfigMap = "metallb-system:config"
 )

@@ -211,6 +213,15 @@ func getPacketConfig(providerConfig string) (packet.Config, error) {
                config.APIServerPort = packet.DefaultAPIServerPort
        }

+       config.BGPNodeSelector = rawConfig.BGPNodeSelector
+       if v := os.Getenv(envVarBGPNodeSelector); v != "" {
+               config.BGPNodeSelector = v
+       }
+
+       if _, err := labels.Parse(config.BGPNodeSelector); err != nil {
+               return config, fmt.Errorf("BGP Node Selector must be valid Kubernetes selector: %w", err)
+       }
+
        return config, nil
 }

diff --git packet/config.go packet/config.go
index 327bb8e..4090214 100644
--- packet/config.go
+++ packet/config.go
@@ -16,6 +16,7 @@ type Config struct {
        AnnotationPeerIPs     string  `json:"annotationPeerIPs,omitEmpty"`
        EIPTag                string  `json:"eipTag,omitEmpty"`
        APIServerPort         int     `json:"apiServerPort,omitEmpty"`
+       BGPNodeSelector       string  `json:"bgpNodeSelector,omitEmpty"`
 }

 // String converts the Config structure to a string, while masking hidden fields.
@@ -39,5 +40,7 @@ func (c Config) Strings() []string {
        ret = append(ret, fmt.Sprintf("local ASN: '%d'", c.LocalASN))
        ret = append(ret, fmt.Sprintf("Elastic IP Tag: '%s'", c.EIPTag))
        ret = append(ret, fmt.Sprintf("API Server Port: '%d'", c.APIServerPort))
+       ret = append(ret, fmt.Sprintf("BGP Node Selector: '%s'", c.BGPNodeSelector))
+
        return ret
 }
```



So I look at the code and I saw that you mainly use env variables and config file for configuring the CCM, so I think I'll skip CLI flag for now.

**Comment by invidian** [comment]
>Hmm, I'm not sure about that smile As your nodeReconciler type currently takes a list of nodes to work on, it does not have a direct access to the informer. Also the timerLoop function currently just lists all nodes and passes them to the nodeReconciler. Any ideas how to approach that in a reasonable way?

Ah, actually `Lister` interface supports passing selector, that would perhaps solve the problem.

**Comment by deitch** [comment]
Rather than surgery, perhaps just filter on the nodes after they are received from the informer? 

On the other hand, if you can find a sane way to pass it in early on, go for it.

**Comment by invidian** [comment]
Created #101 with initial implementation.
