### ISSUE TITLE
Update Kubernetes dependencies to fix printing "unable to load initial CA bundle for" warning

### ISSUE THREAD

**Issue by invidian** [packethost/packet-ccm#113]
Specifically to include https://github.com/kubernetes/kubernetes/commit/413960e49bea4b5558ea4dda3d18137eceaf7f16#diff-cede7efa8beef64baa0651bd73b39e27ad9508763719b48b4d88483a61964c89, as currently following warning is being printed for no reason:
```
W1203 10:38:04.249751       1 configmap_cafile_content.go:102] unable to load initial CA bundle for: "client-ca::kube-system::extension-apiserver-authentication::client-ca-file" due to: configmap "extension-apiserver-authentication" not found
W1203 10:38:04.249802       1 configmap_cafile_content.go:102] unable to load initial CA bundle for: "client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file" due to: configmap "extension-apiserver-authentication" not found
```

**Comment by detiber** [comment]
I'm currently attempting to update the dependencies, wish me luck :joy:

**Comment by invidian** [comment]
Good luck! :smile: Maybe you find https://github.com/kubernetes-sigs/clientgofix useful? I never used it, but found it some time ago.
