### ISSUE TITLE
Cannot deploy loadbalancer.yaml - server reported 404 Not Found, status code=404

### ISSUE THREAD

**Issue by alexellis** [packethost/packet-ccm#114]
Whilst following the README I ran into the following error:

```
root@ccm-test-1:~# kubectl apply -f https://github.com/packethost/packet-ccm/releases/download/${RELEASE}/loadbalancer.yaml
error: unable to read URL "https://github.com/packethost/packet-ccm/releases/download/v1.1.0/loadbalancer.yaml", server reported 404 Not Found, status code=404
root@ccm-test-1:~# 
```

**Comment by rawkode** [comment]
@alexellis The `loadbalancer.yaml` is only released as an artifact for `v2.0.0`


https://github.com/packethost/packet-ccm/releases/download/v2.0.0/loadbalancer.yaml

**Comment by alexellis** [comment]
Could we get the README updated with an example that works, or have it say the above?

![errata](https://user-images.githubusercontent.com/6358735/101045334-1c2d2380-3578-11eb-9c87-61921346a5a6.png)

**Comment by alexellis** [comment]
Thanks @deitch
