### ISSUE TITLE
LoadBalancer enabling behaviours - what is the correct UX

### ISSUE THREAD

**Issue by deitch** [packethost/packet-ccm#117]
Currently, the ccm has an option to manage loadbalancers, specifically metallb.

The ccm takes the job of:

1. interfacing with the Packet API to get an EIP to assign to to a `Service type=LoadBalancer`
1. attaching that EIP to the `Service`, specifically `Spec.Status.LoadBalancerIP`
1. interfacing with the Packet API to enable BGP on the project and per-device
1. placing BGP information on each node's annotations

Note that none of the above has anything to do with a specific implementation (metallb). Packet is unique in that it could have multiple different loadbalancer implementations. Unlike AWS (ELB) or other providers, it isn't tightly tied to one.

In addition, because the (current) LB implementation _is_ metallb, it also does:

5. manage the metallb configmap by placing the bgp and service information in it

Since the two - general lb requirements (list of first 4); metallb-specific (last 1) - have been closely intertwined, ccm has used the existence of the configmap as a "switch" to determine whether or not to do the rest. The UI looks something like this. It is controlled via the value of the configmap flag, env var `PACKET_LB_CONFIGMAP` or equivalent.

* `disabled` - do nothing, do not try to manage the metallb configmap (item 5), but also don't do any non-metallb stuff (items 1-4)
* `` (empty) - default to the metallb default, `metallb-system:config`
* `<something:else>` - use that as the config map namespace+name

If the field is not `disabled` and not empty, then:

* if the `configmap` exists, manage that configmap (item 5) and the other non-metallb stuff (items 1-4)
* if the `configmap` does not exist, do not manage any configmap (item 5) or any of the other non-metallb stuff (items 1-4)

My contention is that we should be able to separate the two lists of metallb-specific and non-metallb-specific, and have a choice to:

* disable everything - we have this now with `PACKET_LB_CONFIGMAP`, which is a bad name for this
* enable just the first list (items 1-4)  - does not exist
* enable the first list (items 1-4) and the second (item 5) - we have this now if the configmap exists and the env var is not `disabled`

Question: what should this configuration look like. How should we tell ccm to pick option a, b or c? Obviously env vars / configs / cli flags, as usual, but what specifically should they be and what should the options be set to?

Let's keep in mind that we may support other LB implementations in the future.

If we can come up with a sane UI with the right flexibility, then we can implement it quickly.

cc @thebsdbox @gianarb @displague @detiber @jmarhee

**Comment by thebsdbox** [comment]
Currently we don't implement the loadbalancer status reply from the `GetLoadBalancer` function, this means that unless something else does it (metal) then there is no way of moving a service from `<pending>` or as below in the service spec:
```
status:
  loadBalancer: {}
```

To remedy this we simply need to update the `GetLoadBalancer` to do:

```
func (l *loadBalancers) GetLoadBalancer(ctx context.Context, clusterName string, service *v1.Service) (status *v1.LoadBalancerStatus, exists bool, err error) {
     if service.Spec.LoadBalancerIP == "SOMETHING that exists" {
			return &v1.LoadBalancerStatus{
				Ingress: []v1.LoadBalancerIngress{
					{
						IP: service.Spec.LoadBalancerIP,
					},
				},
			}, true, nil
    }
   return nil, false, nil
}
```

**Comment by thebsdbox** [comment]
I did find that the `<something:else>` - use that as the config map namespace+name is still expecting a configMap of the same format as metallb.. We could perhaps update the docs to reflect that?

**Comment by displague** [comment]
How would you feel about the configmap being mounted to the pod if you want the feature enabled, and not mounted to the pod if you don't?  Helm/Kustomize/comments could toggle this mount point.

This does two minor things:
* avoids the variable and argument naming concerns
* avoids #115, because if the configmap did not exist the CCM would not start until the configmap volume was removed

Where would the configmap mount?
Would we still want CLI args and ENV variables to disable the behavior when a valid metallb config is mounted?
Would this accommodate KubeVip and others?
Is this approach less intuitive?

**Comment by displague** [comment]
@thebsdbox 
> this means that unless something else does it (metal) then there is no way of moving a service from <pending>

I believe that is the intention, the CCM does not provide loadbalancer features directly, it acts as a helper for other tools.
https://github.com/packethost/packet-ccm/blob/master/packet/cloud.go#L132-L137

**Comment by deitch** [comment]
> How would you feel about the configmap being mounted to the pod if you want the feature enabled, and not mounted to the pod if you don't? Helm/Kustomize/comments could toggle this mount point.

My issue with it is that it requires modifying the deployment manifest and "finagling" with the deployment of a system component. The current one is simply `kubectl apply -f deployment.yaml` which we generate.

We _could_ use helm/kustomize/etc., but that is not very intuitive. We could create a "manifest generator" like weave does for their weavenet manifests, but I don't like the idea of building and managing that service.

**Comment by deitch** [comment]
> Currently we don't implement the loadbalancer status reply from the GetLoadBalancer function, this means that unless something else does it (metal) then there is no way of moving a service from <pending> or as below in the service spec:

That is something we have wanted to do, but it requires being careful, because there are so many other dependencies currently in our once-per-minute loop. It is the "right thing to do", though.

**Comment by deitch** [comment]
> I did find that the <something:else> - use that as the config map namespace+name is still expecting a configMap of the same format as metallb.. We could perhaps update the docs to reflect that? Perhaps PACKET_LB_CONFIGMAP should just be METAL_LB_CONFIGMAP. If it's changed then it's a case of looking for the metallb config elsewhere or if set to disabled then the CCMs job now is to merely watch services, request EIPs and update services based on the results.

Hmm, I like this. Then the var is specifically to working with metallb, and we might have a different env var to pass a setting that involves kube-vip (or something else). Beginnings of a quasi-pluggable mechanism.

Let's take this a bit further. 

Should the bgp and other items (items 1-4 above) be enabled if we are not using metallb? Could there be a different loadbalancer that does not use bgp at all? 

Let's pretend we have 3 load balancer implementations: metallb, kube-vip, eqxlb (I just looked in my crystal ball, and saw that 12 months from now, Equinix will offer their own managed load balancer 😁).

* metallb: I want to do the bgp parts (items 1-4) and configmap (item 5)
* kube-vip: I want to do the bgp parts (items 1-4) and some other step (new item 6)
* eqxlb: I want to use the EM API to do get an EIP (item 1) and create the eqxlb with the EIP attached (new item 7)

I _could_ create different ccm implementations, but the vast majority of it overlaps in all use cases, and I have never seen a cloud provider with different ccm's, so ruling that out.

Here are some possibilities. I use env vars for all, but the data can be passed in other ways.

### Master env var

We have one "master" env var that controls everything, so we would do `PACKET_LB=<type>://<details>`,  where `<details>` is context-dependent e.g.:

* `metallb://metallb-system:config` enables it for metallb (all of the desired steps, 1-4 and 5), using the configmap `config` in the namespace `metallb-system`
* `kube-vip://<something>` enables it for kube-vip (all of the desired steps 1-4 and the new step 6, if it exists); I don't know yet what specific info kube-vip would need
* `eqxlb://<something>` enables it for eqxlb (item 1) and creates the eqxlb with the EIP (new item 7)

If something has not detail, just need so be turned on or off, then it has not detail after the name, either `foolb` or `foolb:` or `foolb://` (I don't care which).

The assumption here is that the selected LB is exclusive; we never would have 2 in parallel. I think we are ok with that, but worth raising.

### Always 1-4

We always do steps 1-4, but have a config for the later steps, so different env vars enable different other steps:

* `METAL_LB_CONFIGMAP` - if blank, do not do step 5; if something real and parsable, look for that configmap, e.g. `METAL_LB_CONFIGMAP=foo-system:config2`. This changes the default from `metallb-system:config` to disabled, but we could have an easy flag, like `METAL_LB_CONFIG=default` goes to the default.
* `KUBE_VIP_DATA` - whatever we need. If blank, do not do step 6; if something real, use it. If no data, then just `default` or `enabled` or `true` as a value.
* `EQX_LB_DATA` - whatever we need. If blank, do not do step 7; if something real, use it. If no data, then just `default` or `enabled` or `true` as a value.

We could do 2 or even all 3 of them, but I cannot think of a use case where that makes sense.

The other problem with this is, what if I do not _want_ bgp enabled? I am doing just eqxlb, which does not need it, or perhaps no LB at all. Why would I have the ccm enable BGP and such? Or why would I have it assign an EIP?

That is why I am sort of leaning towards the `PACKET_LB` env var solution. We also can have an option that is, `enabled`, which basically does only steps 1-4, but skips LB-specific ones. It does all of the bgp stuff for you, and gets and assigns an EIP, but nothing else.

Thoughts?

**Comment by thebsdbox** [comment]
>Should the bgp and other items (items 1-4 above) be enabled if we are not using metallb? Could there be a different loadbalancer that does not use bgp at all? 

Yes, but enabling BGP won't harm anything (I think) + we would more than likely still need to request an EIP. The load-balancer pod (kube-vip, eqxLB) has the job of doing the exposing of the EIP (could be through the API attachment, VPN or ARP etc..)

Also point 2 in the initial post needs updating.. the CCM doesn't update the Status (which is the problem).. it only updates the spec :-) 

Todays "Configmap" support is merely in a format that is only metallb .. and unless we plan on supporting other configMap schemas the naming should probably reflect that? 

For today I think the CCM should default to metallb and the parsing of its Configmap (location configurable by a flag/env) or it doesn't touch anything other than Kubernetes services with the results for adding or removing EIPs.

**Comment by deitch** [comment]
> Yes, but enabling BGP won't harm anything (I think) + we would more than likely still need to request an EIP. The load-balancer pod (kube-vip, eqxLB) has the job of doing the exposing of the EIP (could be through the API attachment, VPN or ARP etc..)

I agree, but I am aware that we have a limited view, mostly what we have done here at EM and other places, mainly via metallb or kube-vip. I would rather not make the assumption.

> Also point 2 in the initial post needs updating.. the CCM doesn't update the Status (which is the problem).. it only updates the spec :-)

Fair enough, as you pointed out in that other WIP PR #121 . 

> Todays "Configmap" support is merely in a format that is only metallb .. and unless we plan on supporting other configMap schemas the naming should probably reflect that?

I cannot think what the other schemas are, and I don't want to at this point. I would much rather have a format that we can expand going forward (other env vars, or other "protocols" in this env var), and then worry about those when they appear.

> For today I think the CCM should default to metallb and the parsing of its Configmap (location configurable by a flag/env) or it doesn't touch anything other than Kubernetes services with the results for adding or removing EIPs.

What does this mean?

**Comment by deitch** [comment]
Do we have more input on this? @displague @thebsdbox @gianarb @detiber ? I would like us to settle on a direction for this and get moving.

**Comment by deitch** [comment]
After some extensive discussions, we are settling on the following behaviour. If anyone has objections, raise them.

By default, ccm will not enable _any_ loadbalancers, or any loadbalancing behaviour. This includes all of the items 1-4 in the original comment, and item 5 or any others. It will do all of the other ccm standard stuff.

You enable loadbalancing behaviour - and all of its ancillary parts - by setting the `PACKET_LB` env var (or configmap item or cli flag). It has a setting of:

```
<type>://<details>
```

where 

* `<type>` is the type of load balancer, e.g. `metallb` or `kube-vip` or any others
* `<details>` is any additional details needed to manage that load balancer type. E.g. metallb needs to be provided the namespace and name of the configmap

If something has no additional details needed, or it has a default, then it can just pass `<type>:` or `<type>://`.

So we might pass:

* `kube-vip://` - it has no additional details for now
* `metallb://foons:config` - use metallb with the configmap `config` in namespace `foons`
* `metallb://` - use the default metallb configmap (`metallb-system:config`)
