### ISSUE TITLE
Periodically reconcile all nodes 

### ISSUE THREAD

**Issue by invidian** [packethost/packet-ccm#131]
To make environment more robust, I think CCM should periodically verify, that all nodes has correct `spec.providerID` set, has BGP enabled etc.

Right now CCM only reacts when node joins or gets removed from the cluster, which is not ideal, as such events might be missed, e.g. when CCM gets updated and it's not available for some time.

Having periodic reconciliation would also help in scenarios when CCM is installed on existing clusters, as right now when one does so, the CCM won't set `providerID` for existing nodes, to workaround that, one must remove and re-register all nodes in the cluster.

**Comment by deitch** [comment]
@invidian actually it already does, at least for part of it. In addition to the `Add` and `Delete` events for the watchers, there is a timer loop that calls reconcile on the services and the nodes for each registered service. Se the timer setting [here](https://github.com/packethost/packet-ccm/blob/7ac41296e3441fa3e711abade500f5a0ac0fe9d5/packet/cloud.go#L135) and the actual implementation [here](https://github.com/packethost/packet-ccm/blob/7ac41296e3441fa3e711abade500f5a0ac0fe9d5/packet/cloud.go#L300-L328). That part includes the bgp, so it sets BGP at the device level and annotations, see [here](https://github.com/packethost/packet-ccm/blob/700051c08793be616f960097bd6887be6d9d4c99/packet/bgp.go#L75-L166).

As far as the provider ID, it doesn't actually set it in the loop. I don't think providerID is set by the CCM, is it? Isn't it a `kubelet` flag?

**Comment by invidian** [comment]
>As far as the provider ID, it doesn't actually set it in the loop. I don't think providerID is set by the CCM, is it? Isn't it a kubelet flag?

`--cloud-provider` flag should be set in `kubelet`. `--provider-id` is not required.

But this is actually my mistake. It's the core CCM which sets `Spec.ProviderID` field, but only if uninitialized taint is set. See: https://github.com/kubernetes/cloud-provider/blob/67ac9f4d3f7b3bec927df636c4573e1159eaac30/controllers/node/node_controller.go#L477-L482.

Thanks for pointing out the timers @deitch. I think everything is fine then, sorry for the confusion!
