### ISSUE TITLE
Expose BGP-related information as node annotations

### ISSUE THREAD

**Issue by johananl** [packethost/packet-ccm#39]
## General

In order for k8s clusters to maintain BGP peering with Packet ToR switches using solutions such as [MetalLB](https://metallb.universe.tf/), it is necessary for k8s controllers to be able to retrieve the following information about a Packet device:

- The local ASN
- The remote ASN
- The peer address

The information above is [available](https://www.packet.com/developers/api/bgp/#bgp-getBgpNeighborData) on the Packet API.

I suggest we add logic in the CCM to "enrich" `Node` objects with BGP-related information using **annotations** since this information is non identifying.

>NOTE: In cases where a **BGP password** is configured for a project, this information is necessary as well in order to successfully establish BGP sessions. However, storing clear-text passwords in `Node` objects isn't a very good idea. A better approach would be to store the password in a k8s **secret**, however secrets are namespace-scoped and the CCM can't know which applications are going to need access to the password. Therefore, I guess we should simply ignore the BGP password at the CCM level. Since BGP passwords aren't node-specific, it seems reasonable to me that users configure a secret themselves and wire the relevant application to use that secret.

cc: @deitch 

## Implementation

I've [discussed](https://kubernetes.slack.com/archives/C718BPBQ8/p1584992638033100) this proposal with SIG Cloud Provider as to date there doesn't seem to be a CCM which adds annotations to `Node` objects. Here is the answer I've received:

>None of the core controllers add labels, but if you need to, you can create a custom one and run it as part of `Initialize` (https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L44-L47)

So looks like this ^ is the right place within the CCM to include the new logic.

Following the k8s [guidelines](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) for label structure, we should select a **prefix**. The following assumes the chosen prefix is `packet.com`, however I have no opinion regarding the actual prefix as long as it's clear it is Packet-specific.

Once implemented, a user who runs a k8s cluster on Packet with the CCM deployed should expect annotations as in the following example to exist on any `Node` object before the `node.cloudprovider.kubernetes.io/uninitialized` taint is removed:

- `packet.com/customer-asn: 65000`
- `packet.com/peer-asn: 65530`
- `packet.com/peer-address: 10.80.3.126`

**Comment by deitch** [comment]
I see no issues with this. I like the clean idea of just adding annotations, which have no side effect and don't bind the ccm changes with anything else.

I do want to raise two issues:

* annotation labels: I agree about a prefix, but would like to try for something a little more generic. ASN info is not Packet-specific, so a more generic label would be great.
* In order to add metallb into Packet CCM (configurable to enable/disable), we already needed to implement a node watcher/modifier loop, see [this PR](https://github.com/packethost/packet-ccm/pull/34). That one is blocked as we are waiting for some changes on the Packet IP management API. However, I want us to take advantage of the node management logic already in there. What I am going to do is use feature flags to disable the load balancer functionality, merge it in, and then we can take advantage of the loops to add the annotations easily.

**Comment by johananl** [comment]
About the generic annotations - SGTM, though I would say this approach hints in the direction of having multiple CCMs (namely not just the Packet CCM) use the same annotations, assuming other CCMs deal with things like BGP ASNs. If that's the case, then we might want to discuss the generic annotations with SIG Cloud Provider, and designate the Packet CCM as the **first** CCM to use these annotations, with the intention that other CCMs gradually adopt the same approach.
That said, there is definitely no *harm* in using generic names. FWIW, as long as the MetalLB implementation allows the user to specify which annotations to get the BGP info from, it shouldn't matter at all what they are called.

Regarding where/how to implement the feature in the Packet CCM, I trust your judgement there. As long as CCM users aren't *forced* to deploy MetalLB, I'm good with your suggestion.

**Comment by deitch** [comment]
> Regarding where/how to implement the feature in the Packet CCM, I trust your judgement there. As long as CCM users aren't forced to deploy MetalLB, I'm good with your suggestion

Yup, that was the plan from the getgo. As it is, it is disabled until Packet API's IP management adds a missing connection (it is being worked on).

> FWIW, as long as the MetalLB implementation allows the user to specify which annotations to get the BGP info from, it shouldn't matter at all what they are called.

Indeed. That is one of the things I liked about your approach. Don't hardcode it into metallb; rather, indicate the annotations in the config file.

> though I would say this approach hints in the direction of having multiple CCMs (namely not just the Packet CCM) use the same annotations, assuming other CCMs deal with things like BGP ASNs

Agreed, although I was thinking not just CCMs. There could be other things that use BGP or network or other annotations. The general idea is to use annotations as a data channel that decouples the API that knows how to find the data (which could vary by cloud provider, service, many other things) from the one that knows how to consume it. This is very similar to the cluster-api-provider concept: use kubernetes concepts (resources or annotations) as the data channel.

I will post into the cloud-provider, but they may send us to one of the others.
