### ISSUE TITLE
Docker multi arch images are not totally right

### ISSUE THREAD

**Issue by gianarb** [packethost/packet-ccm#45]
Hello
I think this screenoshot from Docker hub explains the issue:

![Screenshot 2020-05-20 at 09 44 04](https://user-images.githubusercontent.com/1630267/82419306-7ce28c00-9a7e-11ea-8592-4796a3aa638f.png)

The image tagged as arm64 gets detected as amd64 arch on hub, I think this prevents images to work on arm.

**Comment by deitch** [comment]
Thanks for reporting this. We will get it in.
