### ISSUE TITLE
Elastic IP management for control plane

### ISSUE THREAD

**Issue by gianarb** [packethost/packet-ccm#57]
Initially, this issue got discussed in [CAPP #141](https://github.com/kubernetes-sigs/cluster-api-provider-packet/issues/141).

## The problem statement: No Load balancer

Packet does not provide a load balancer, it means that you have to figure out a way to route traffic between Control Planes when running Kubernetes in HA otherwise you will end up having a single point of failure (SPOF) even if you run k8s HA. Because only the Node that has the Elastic IP attached to it gets traffic.

When looking at how other cloud providers solve this issue it is clear that an externally managed load balancer will make this implementation straightforward. Your cluster gets a load balancer and all the control planes are registered there.

## But we do not have a load balancer

We evaluated a couple of different ways originally to get around this problem, I will summarize them here

1. BGP at Control Plane device level with bird or equivalent. This will may work but it will conflict with MetalLB. The load balancer implementation that we ship with Kubernetes via CCM #53 because we will end up having two BGP communications ongoing from the same node, one from bird and one from MetalLB. This can potentially confuse the router.

2. MetalLB for Control Plane. This is a nice and clean solution in theory, but in practice, it is hard to implement. You need to have a  control plane up and running in order to place a Service type=LoadBalancer (managed by MetalLB) in front of the API Servers. But you can not have a reachable API Server until you get the right ElasticIP assigned to the Load Balancer. 🔁 

3. Write a control loop based on time (every 6sec for example) that will check the status of the ElasticIP, if it does not respond it can be attached to another control plane because it means that the current one is broken.

We discussed the pros and cons in the other issue linked above.

## This is a CCM issue... maybe

We are moving the conversation here because we think this is a better home for this kind of feature. Kubernetes HA on Packet is something that does not require ClusterAPI. Kubernetes clusters can be provisioned via Terraform or other tools. Fixing this issue here will make everybody using Kubernetes on Packet and CCM capable of using this feature.

**Comment by deitch** [comment]
This is a good summary of the issue. Here is what we agreed between us on the call:

* CCM will be responsible for managing an EIP's attachment to a control plane node _if the EIP exists already_
* CCM will have a default tag that it will look for on the EIP, configurable
* If no EIP exists with the provided tag, CCM will log a message like, "no EIP with tag <tag> found, EIP management disabled" (or similar)and ignore it
* during its timed control loop, CCM will do the following:
   * get the EIP with the provided tag from the Packet API
   * get the control plane nodes from the k8s API
   * attempt to reach the control plane health check URL on each node on their IP:port, and via the EIP:port
   * if all nodes succeed and EIP fails, nothing to do, log a message
   * if the EIP fails and the node it is connected to fails, switch the EIP to a working node
* CCM can have the tag to use set to override the default. It can be set using the env var `PACKET_EIP_TAG` or from the secret with the property `eipTag`
* The retries between attempts and timeout should be configurable, but can start hard-coded.

Note that it can take long enough to test all of the nodes and the EIP, with retries and backoff, that this should have a conflict resolver. E.g. in the loop, before starting a new range of health checks, first check if one is in process.

**Comment by gianarb** [comment]
> CCM will have a default tag that it will look for on the EIP, configurable

This changed along the way, we won't have a default tag as far as I know because we will use the empty configuration as a way to enable/disable the feature itself.

**Comment by deitch** [comment]
Updated.
