### ISSUE TITLE
Release v1.1.0 does not have loadbalancer.yaml

### ISSUE THREAD

**Issue by knrt10** [packethost/packet-ccm#84]
`curl https://github.com/packethost/packet-ccm/releases/download/v1.1.0/loadbalancer.yaml` throws not found.

**Comment by deitch** [comment]
Correct it doesn't. We will be cutting a new release shortly. We have one other patch waiting to go in, and then we will cut it.

**Comment by knrt10** [comment]
Thank you for the information and quick response.
