### ISSUE TITLE
Unable to list configmaps in metallb-system namespace by cloud-controller-manager SA

### ISSUE THREAD

**Issue by knrt10** [packethost/packet-ccm#85]
I am trying to integrate packet-ccm with Lokomotive. I tried to run it standalone by running the deployment from `v1.1.0` release and for load balancer using Lokomotive's [MetalLb](https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/components/metallb.md) component. But when I deploy it logs says

```sh
failed to update and sync nodes: failed to get metallb config map: unable to get metallb configmap config: configmaps "config" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "metallb-system"
```

Can someone please tell, if I am doing something wrong?

### Steps to reproduce:

- Deployed cluster using Lokomotive latest release v0.5.0 by setting `--cloud-provider=external` for kubelet
- created secret as specfied in packet-ccm docs
- applied v1.1.0 deployment
- applied lokomotive MetalLb component

**Comment by deitch** [comment]
Correct. This is a bug with v1.1.0. This is fixed in the mainline master branch Pull Request #80 , and will be in a new release (v2.0.0) due to be cut very shortly (hoping this week).

We can leave this open until the release is cut.

**Comment by knrt10** [comment]
Closing, as this is fixed with the latest release
