### ISSUE TITLE
re-applying Lokomotive's MetalLB fails ccm

### ISSUE THREAD

**Issue by knrt10** [packethost/packet-ccm#93]
### Steps to reproduce

- Apply secrets
- Apply [deployment](https://github.com/packethost/packet-ccm/blob/master/deploy/template/deployment.yaml) on cluster with kubelet configured.
- Apply [Lokomotive MetalLb](https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/components/metallb.md) component. 

If component is re-applied, ccm does not pick configMap correctly and throws error that configMap is not correct, which should not happen. You have to delete the pod manually to get it to work again.

```sh
failed to update and sync nodes: failed to get metallb config map: could not parse config: yaml: unmarshal errors:
  line 1: field peer-autodiscovery not found in type metallb.ConfigFile
```

cc @deitch

**Comment by deitch** [comment]
yeah, we `UnmarshalStrict`; I don't see any reason why we cannot be more relaxed about.
