### ISSUE TITLE
Add packet secret template to releases

### ISSUE THREAD

**Issue by enkelprifti98** [packethost/packet-ccm#99]
https://github.com/packethost/packet-ccm/blob/master/deploy/template/secret.yaml

It would be helpful to have this secret template used by the CCM in the releases page:

https://github.com/packethost/packet-ccm/releases

**Comment by displague** [comment]
I've added some text to https://github.com/packethost/packet-ccm/releases/tag/v2.0.0 which may be closer to what you are expecting. The format of the secret has not changed in recent releases, so I don't feel that we need to call that out on this 2.0.0 release. Nonetheless, I linked to our installation instructions (which do include that template) and the updated release notes call out the secret format (included in the installation instructions).

Feel free to reopen, @enkelprifti98 .
